version: '3'

services: 
  apache:
    build: ./apache
    ports: 
      - 80:80
    environment: 
      - DB_HOST=mariadb
      - DB_NAME=${MARIADB_DATABASE}
      - DB_USER=${MARIADB_USER}
      - DB_PASSWORD=${MARIADB_PASSWORD}
    volumes:
      - ./src:/var/www/html
    depends_on:
      - mariadb

  mariadb:
    image: mariadb
    ports:
      - 3306:3306
    environment: 
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MARIADB_DATABASE=${MARIADB_DATABASE}
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
      - LANG=C.UTF-8
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d 
    restart: always
  
  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8080:80
    environment:
      - PMA_HOST=mariadb
    depends_on: 
      - mariadb
volumes:
  mariadb_data:
  